### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alandipert** [Chouser/clojure-jna#1]
Hi Chris, this is a great library, and I would like to work on it and include it in a commercial project.  It would be really helpful to me for it to be distributed under a license.  LGPL or EPL would work :-)

Thanks,
Alan

**Comment by Chouser** [comment]
Sorry it took me so long to respond to this.

The clojure_jna.clj file itself already has authorship, copyright, and license info (EPL), so you should be covered to proceed already, but I'll add a LICENSE file to help clarify the situation.

**Comment by alandipert** [comment]
Thanks!
